version: '3.3'
services:
  sales-score:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./salesScoreSystem/:/app
    command: ./mvnw spring-boot:run

  postgresDB:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=salesScore
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d
volumes:
  postgres_data:
  postgres_config: